### ISSUE TITLE
Skipping Fragment

### ISSUE THREAD

**Issue by Orotachi** [abhiTronix/azure_video_downloader#2]
![Powershell snapshot](https://user-images.githubusercontent.com/63191988/93564595-930a4580-f9a7-11ea-9c52-3dafd05d6f9a.png)

Why is it skipping some fragments?

**Comment by abhiTronix** [comment]
> Why is it skipping some fragments?

@Orotachi Seems like your network is not working properly, or connection is resetted by the server.
