### ISSUE TITLE
I cant download.

### ISSUE THREAD

**Issue by Abdullah-Bhutta** [abhiTronix/azure_video_downloader#4]
Hi, 

I followed all your detailed steps and still couldn't be able to download the file.
Can you confirm that this file can be downloaded through your software?
Link:- https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/
You can include manifest at the end, but your program doesn't support manifest files.

@abhiTronix 

Plz fix and help.

**Comment by abhiTronix** [comment]
@Abdullah-Bhutta Can you paste the error from the terminal?

**Comment by Abdullah-Bhutta** [comment]
> @Abdullah-Bhutta Can you paste the error from the terminal?

Sir, were you able to download it?

Will post error soon.

**Comment by Abdullah-Bhutta** [comment]
> @Abdullah-Bhutta Can you paste the error from the terminal?

@abhiTronix  Here you go sir.

PS C:\Users\Abdullah\Downloads\azure_video_downloader> python -m pip install --user -r requirements.txt
Collecting youtube_dl>=2020.9.14
  Using cached youtube_dl-2021.6.6-py2.py3-none-any.whl (1.9 MB)
Installing collected packages: youtube-dl
  WARNING: The script youtube-dl.exe is installed in 'C:\Users\Abdullah\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed youtube-dl-2021.6.6

PS C:\Users\Abdullah\Downloads\azure_video_downloader> python azure_downloader.py -i https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism
[generic] manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf): Downloading webpage
[generic] manifest(format=mpd-time-csf): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\generic.py", line 2525, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Abdullah\Downloads\azure_video_downloader\azure_downloader.py", line 260, in <module>
    ydl.download([inputs])
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by abhiTronix** [comment]
> @abhiTronix
Sir, were you able to download it?

@Abdullah-Bhutta No I'm getting 403 forbidden, since link is expired or geotagged.

**Comment by Abdullah-Bhutta** [comment]
> > @abhiTronix
> > Sir, were you able to download it?
> 
> @Abdullah-Bhutta No I'm getting 403 forbidden, since link is expired or geotagged.

Link is not expired, link is the same. But it might be Geotagged with Pakistan. 

So, Can you Please Use a VPN or suggest me another method, you think of; while you look at the above code.

**Comment by abhiTronix** [comment]
> ERROR: No video formats found;

@Abdullah-Bhutta Did you updated the youtube-dl? If not, then use this command:
```sh
python -m pip install -r -U --user youtube-dl
```

Also, how you extracted this `.ism` url? through browser or something else.

**Comment by abhiTronix** [comment]
> So, Can you Please Use a VPN or suggest me another method, you think of; while you look at the above code.

@Abdullah-Bhutta That's not needed. We can solve it at your end.

**Comment by Abdullah-Bhutta** [comment]
> ```shell
> python -m pip install  -U --user youtube-dl
> ```

Yeah, i downloaded it today again.

with running the above command, it shows:- 

PS C:\Users\Abdullah\Downloads\azure_video_downloader> python -m pip install  -U --user youtube-dl
Requirement already satisfied: youtube-dl in c:\users\abdullah\appdata\roaming\python\python39\site-packages (2021.6.6)

{END}

I extracted the URL from the Networks Tab in my browser, while running the video, video was being downloaded in chunks.

And this was the initiator to bring those files.  https://amp.azure.net/libs/amp/2.2.0/azuremediaplayer.min.js

PLZ HELP

**Comment by abhiTronix** [comment]
@Abdullah-Bhutta Are you using some username and password on video's website?

**Comment by Abdullah-Bhutta** [comment]
> @Abdullah-Bhutta Are you using some username and password on video's website?

Yes, but when i put the same link on Azure's Web Player, it works, 
Here have a look:- https://ampdemo.azureedge.net/?url=https%3A%2F%2Fvideoengine.punjabcollege.net%2Ff594a712-3ecf-4fdc-a234-f8bf4eaed83c%2Fphy1ch2lect10-new.ism%2Fmanifest
But if I don't put manifest at the end of the URL, it doesn't work. (.ism/manifest). Only .ism at the end doesn't work

**Comment by abhiTronix** [comment]
@Abdullah-Bhutta Can you change this line

https://github.com/abhiTronix/azure_video_downloader/blob/8145a12ae25e3a1ea0345d4c397ac8050de29dfb/azure_downloader.py#L257

to 

```python
        inputs += "/manifest"
```

and then try downloading it?

**Comment by Abdullah-Bhutta** [comment]
> @Abdullah-Bhutta Can you change this line: _(change directly in your local script)_
> 
> https://github.com/abhiTronix/azure_video_downloader/blob/8145a12ae25e3a1ea0345d4c397ac8050de29dfb/azure_downloader.py#L257
> 
> to
> 
> ```python
>         inputs += "/manifest"
> ```
> 
> and then try downloading it?

I did that, but cant download.
Here have a look.:-

PS C:\Users\Abdullah\Downloads\azure_video_downloader> python azure_downloader.py -i https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\generic.py", line 2508, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\extractor\common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Abdullah\Downloads\azure_video_downloader\azure_downloader.py", line 260, in <module>
    ydl.download([inputs])
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Abdullah\AppData\Roaming\Python\Python39\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


PS C:\Users\Abdullah\Downloads\azure_video_downloader> python azure_downloader.py -i https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/manifest
Traceback (most recent call last):
  File "C:\Users\Abdullah\Downloads\azure_video_downloader\azure_downloader.py", line 152, in <module>
    assert str(inputs).endswith(".ism"), "Invalid Input `-i/--input` URL provided!"
AssertionError: Invalid Input `-i/--input` URL provided!


ORIGNAL LINK looks, like this: (un-edited):-  https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/QualityLevels(127000)/Fragments(aac_eng_2_127_2_1=360960000,format=mpd-time-csf)

**Comment by abhiTronix** [comment]
>  https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/QualityLevels(127000)/Fragments(aac_eng_2_127_2_1=360960000,format=mpd-time-csf)

@Abdullah-Bhutta  this URL only points to audio stream. Are there any video fragment also?

**Comment by Abdullah-Bhutta** [comment]
> > https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/QualityLevels(127000)/Fragments(aac_eng_2_127_2_1=360960000,format=mpd-time-csf)
> 
> @Abdullah-Bhutta this URL only points to audio stream. Are there any video fragment also? Such as `Fragments(video=60000000,format=mpd-time-csf)` ?

Yes Sir,
But the link we need, is the same. 

https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/QualityLevels(1123000)/Fragments(video=360000000,format=mpd-time-csf)

**Comment by abhiTronix** [comment]
> But the link we need, is the same.
> 
> https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/QualityLevels(1123000)/Fragments(video=360000000,format=mpd-time-csf)

@Abdullah-Bhutta This makes no sense. I tested with number of sites and its working like https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/QualityLevels(127999)/Fragments(aac_UND_2_127=i,format=mpd-time-csf):
```sh
PS C:\Users\abhisys\azure_video_downloader> py azure_downloader.py -i https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism
WARNING: FFmpeg not available, thereby Audio/Video streams will not be merged!
[generic] manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf): Downloading webpage
[generic] manifest(format=mpd-time-csf): Extracting information
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
[dashsegments] Total fragments: 91
[download] Destination: C:\Users\abhiu\azure_video_downloader\output\AzureMediaServicesPromo.f1_V_video_2.mp4
[download] 100% of 39.32MiB in 01:19
[dashsegments] Total fragments: 91
[download] Destination: C:\Users\abhiu\azure_video_downloader\output\AzureMediaServicesPromo.f5_A_aac_UND_2_127_1.m4a
[download] 100% of 2.81MiB in 01:11
```

**Comment by Abdullah-Bhutta** [comment]
> > But the link we need, is the same.
> > https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/QualityLevels(1123000)/Fragments(video=360000000,format=mpd-time-csf)
> 
> @Abdullah-Bhutta This makes no sense. I tested with number of sites and its working like https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/QualityLevels(127999)/Fragments(aac_UND_2_127=i,format=mpd-time-csf):
> 
> ```shell
> PS C:\Users\abhisys\azure_video_downloader> py azure_downloader.py -i https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism
> WARNING: FFmpeg not available, thereby Audio/Video streams will not be merged!
> [generic] manifest(format=mpd-time-csf): Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] manifest(format=mpd-time-csf): Downloading webpage
> [generic] manifest(format=mpd-time-csf): Extracting information
> WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
> [dashsegments] Total fragments: 91
> [download] Destination: C:\Users\abhiu\azure_video_downloader\output\AzureMediaServicesPromo.f1_V_video_2.mp4
> [download] 100% of 39.32MiB in 01:19
> [dashsegments] Total fragments: 91
> [download] Destination: C:\Users\abhiu\azure_video_downloader\output\AzureMediaServicesPromo.f5_A_aac_UND_2_127_1.m4a
> [download] 100% of 2.81MiB in 01:11
> ```

How come you are downloading the same file as MP4 and i on the other hand have .ismv ????

And i dont know why my link doesnt work. Can try another one, if you like. But it says that no-supported format was found.

**Comment by abhiTronix** [comment]
> How come you are downloading the same file as MP4 and i on the other hand have .ismv ????

@Abdullah-Bhutta Can you screenshot it?

**Comment by Abdullah-Bhutta** [comment]
> > How come you are downloading the same file as MP4 and i on the other hand have .ismv ????
> 
> @Abdullah-Bhutta Can you screenshot it?

PS C:\Users\Abdullah\Downloads\azure_video_downloader> python azure_downloader.py -i https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
[ism] Total fragments: 90
[download] Destination: C:\Users\Abdullah\Downloads\azure_video_downloader\output\AzureMediaServicesPromo.f1836.ismv
[download] 100% of 39.32MiB in 05:26
[ism] Total fragments: 90
[download] Destination: C:\Users\Abdullah\Downloads\azure_video_downloader\output\AzureMediaServicesPromo.faac_UND_2_127-127.isma
[download] 100% of 2.82MiB in 03:01
[ffmpeg] Merging formats into "C:\Users\Abdullah\Downloads\azure_video_downloader\output\AzureMediaServicesPromo.ismv"
Deleting original file C:\Users\Abdullah\Downloads\azure_video_downloader\output\AzureMediaServicesPromo.f1836.ismv (pass -k to keep)
Deleting original file C:\Users\Abdullah\Downloads\azure_video_downloader\output\AzureMediaServicesPromo.faac_UND_2_127-127.isma (pass -k to keep)

END

**Comment by abhiTronix** [comment]
@Abdullah-Bhutta Did you rolled back the modifications you made earlier in your script?

**Comment by Abdullah-Bhutta** [comment]
> > How come you are downloading the same file as MP4 and i on the other hand have .ismv ????
> 
> @Abdullah-Bhutta Can you screenshot it?

But when i put my link into the Azure webplayer, it plays normally, and under links, the link is also the same.
https://aka.ms/azuremediaplayer?url=https%3A%2F%2Fvideoengine.punjabcollege.net%2Ff594a712-3ecf-4fdc-a234-f8bf4eaed83c%2Fphy1ch2lect10-new.ism%2Fmanifest

**Comment by Abdullah-Bhutta** [comment]
> @Abdullah-Bhutta Did you rolled back the modifications you made earlier in your script?

No, i kept it same

**Comment by abhiTronix** [comment]
> No, i kept it same

Do that first then only you can get same output as mine. Anyways, IDK Problem here is in youtube-dl's compatibility with https://videoengine.punjabcollege.net urls. Did you tries IDM downloader instead, it got free trial on windows.

**Comment by Abdullah-Bhutta** [comment]
> @Abdullah-Bhutta Did you rolled back the modifications you made earlier in your script?

I reverted the changes, and now its downloading mp4 format.

But I canot benefit from it as, this shows error, while downloading my link

**Comment by Abdullah-Bhutta** [comment]
> > No, i kept it same
> 
> Do that first then only you can get same output as mine. Anyways, IDK Problem here is in youtube-dl's compatibility with https://videoengine.punjabcollege.net urls. Did you tries IDM downloader instead, it got free trial on windows.

IDM downloader for extracting the link?

**Comment by abhiTronix** [comment]
> IDM downloader for extracting the link?

Yes, but It can download too.

**Comment by Abdullah-Bhutta** [comment]
> > IDM downloader for extracting the link?
> 
> Yes, but It can download too.

Note:- I am not using any kind of username or account for this video playback info,
![Screenshot 2021-06-08 122444](https://user-images.githubusercontent.com/85538214/121141622-9fe00980-c854-11eb-9c34-38729dd96024.png)

**Comment by Abdullah-Bhutta** [comment]
> > But the link we need, is the same.
> > https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/QualityLevels(1123000)/Fragments(video=360000000,format=mpd-time-csf)
> 
> @Abdullah-Bhutta This makes no sense. I tested with number of sites and its working like https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/QualityLevels(127999)/Fragments(aac_UND_2_127=i,format=mpd-time-csf):
> 
> ```shell
> PS C:\Users\abhisys\azure_video_downloader> py azure_downloader.py -i https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism
> WARNING: FFmpeg not available, thereby Audio/Video streams will not be merged!
> [generic] manifest(format=mpd-time-csf): Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] manifest(format=mpd-time-csf): Downloading webpage
> [generic] manifest(format=mpd-time-csf): Extracting information
> WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
> [dashsegments] Total fragments: 91
> [download] Destination: C:\Users\abhiu\azure_video_downloader\output\AzureMediaServicesPromo.f1_V_video_2.mp4
> [download] 100% of 39.32MiB in 01:19
> [dashsegments] Total fragments: 91
> [download] Destination: C:\Users\abhiu\azure_video_downloader\output\AzureMediaServicesPromo.f5_A_aac_UND_2_127_1.m4a
> [download] 100% of 2.81MiB in 01:11
> ```

So, my video and your downloaded video are both in 540p 1.8Mbps rather than full resolution which is 720p 2.8Mbps.
Any clue?

**Comment by abhiTronix** [comment]
> So, my video and your downloaded video are both in 540p 1.8Mbps rather than full resolution which is 720p 2.8Mbps.
Any clue? 

@Abdullah-Bhutta You can easily change to max quality by flags but that's not he problem here.

**Comment by abhiTronix** [comment]
@Abdullah-Bhutta  Can you post the output of this command?

```sh
youtube-dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism//manifest(format=mpd-time-csf)'
```

**Comment by Abdullah-Bhutta** [comment]
> > So, my video and your downloaded video are both in 540p 1.8Mbps rather than full resolution which is 720p 2.8Mbps.
> > Any clue?
> 
> @Abdullah-Bhutta You can easily change to max quality by flags but that's not he problem here.

how exactly?

**Comment by Abdullah-Bhutta** [comment]
> > how exactly?
> 
> `--quality high`

where do i put this command?
Can you guide completely?
I will be very grateful to you for the favors you are doing for me.👏👏👏🤗🤗

**Comment by Abdullah-Bhutta** [comment]
> ```shell
> youtube-dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism//manifest(format=mpd-time-csf)'
> ```

PS C:\Users\Abdullah\Downloads\azure_video_downloader> youtube-dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism//manifest(format=mpd-time-csf)'
youtube-dl : The term 'youtube-dl' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ youtube-dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4f ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (youtube-dl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Abdullah-Bhutta** [comment]
> @Abdullah-Bhutta Use this instead:
> 
> ```shell
> python -m youtube-dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism//manifest(format=mpd-time-csf)'
> ```
C:\Users\Abdullah\AppData\Local\Programs\Python\Python39\python.exe: No module named youtube-dl

**Comment by abhiTronix** [comment]
> C:\Users\Abdullah\AppData\Local\Programs\Python\Python39\python.exe: No module named youtube-dl

@Abdullah-Bhutta 💢 !!!, change `youtube-dl` to `youtube_dl` in this command

**Comment by abhiTronix** [comment]
@Abdullah-Bhutta  By bad URL was wrong. Try this:

```sh
python -m youtube_dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/manifest(format=mpd-time-csf)'
```

**Comment by Abdullah-Bhutta** [comment]
> @Abdullah-Bhutta By bad URL was wrong. Try this:
> 
> ```shell
> python -m youtube_dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/manifest(format=mpd-time-csf)'
> ```

PS C:\Users\Abdullah\Downloads\azure_video_downloader> python -m youtube_dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/manifest(format=mpd-time-csf)'
[generic] manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf): Downloading webpage
[generic] manifest(format=mpd-time-csf): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by abhiTronix** [comment]
> PS C:\Users\Abdullah\Downloads\azure_video_downloader> python -m youtube_dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism//manifest(format=mpd-time-csf)'
[generic] manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf): Downloading webpage
[generic] manifest(format=mpd-time-csf): Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


OK bug is confirmed Something is wrong this URLs compatibility with youtube-dl itself and I don't think we can do much here as  maybe hidden in youtube-dl source code. You must reach out to youtube-dl devs by raising issue here: https://github.com/ytdl-org/youtube-dl/issues and ask them why `python -m youtube_dl -F 'https://videoengine.punjabcollege.net/f594a712-3ecf-4fdc-a234-f8bf4eaed83c/phy1ch2lect10-new.ism/manifest(format=mpd-time-csf)'` is not working but `python -m youtube_dl -F "https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest(format=mpd-time-csf)"` is working just fine:

```sh
python -m youtube_dl -F "https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest(format=mpd-time-csf)"
[generic] manifest(format=mpd-time-csf): Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf): Downloading webpage
[generic] manifest(format=mpd-time-csf): Extracting information
[info] Available formats for manifest(format=mpd-time-csf):
format code          extension  resolution note
5_A_aac_UND_2_127_1  m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2 (48000Hz)
1_V_video_6          mp4        320x180    DASH video  357k , mp4_dash container, avc1.64000D, video only
1_V_video_5          mp4        640x360    DASH video  585k , mp4_dash container, avc1.64001E, video only
1_V_video_4          mp4        640x360    DASH video  863k , mp4_dash container, avc1.64001E, video only
1_V_video_3          mp4        960x540    DASH video 1291k , mp4_dash container, avc1.64001F, video only
1_V_video_2          mp4        960x540    DASH video 1836k , mp4_dash container, avc1.64001F, video only
1_V_video_1          mp4        1280x720   DASH video 2790k , mp4_dash container, avc1.64001F, video only (best)
```

Goodluck!

**Comment by Abdullah-Bhutta** [comment]
Can you tell me how you got the video resolution option?
And which code are you using?
And which software to run the code?
and how do i select the High res option?
PLZ give me with an above example.

**Comment by abhiTronix** [comment]
@Abdullah-Bhutta Just do `python azure_downloader.py -i https://amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism -q high`

**Comment by Abdullah-Bhutta** [comment]
@abhiTronix  So, you think that something is wrong with my URL's?

**Comment by abhiTronix** [comment]
Yes.

**Comment by Abdullah-Bhutta** [comment]
Can you do something about it?

**Comment by abhiTronix** [comment]
Told you above. Ask Youtube-dl developers, they'll fix this bug.

**Comment by Abdullah-Bhutta** [comment]
> Told you above. Ask Youtube-dl developers, they'll fix this bug.

How much time can it take?
